### ISSUE TITLE
[solved] TLS SMTP 无法发送邮件

### ISSUE THREAD

**Issue by subver** [open-falcon/mail-provider#12]
你好，报错信息为：unencrypted connection
请问怎么解决呀。谢谢！
另外，我们需要免登陆发送邮件，这个模块是否支持呢？

**Comment by mognum** [comment]
同样遇到这个报错

**Comment by freedomkk-qfeng** [comment]
这个说明邮件系统不支持 StartTLS，golang 的 smtp 模块不允许非加密的 SMTP 请求。
请更新 mail-provider 到最新版本，然后启用 TLS 模式用加密端口尝试。
免登录发送也可以在新版本下使用匿名模式发送（需要邮件系统做白名单支持)
