### ISSUE TITLE
单机安装的falconplus，mailprovider修改配置后，一起动就停止？

### ISSUE THREAD

**Issue by phantoo0809** [open-falcon/mail-provider#14]
laiwei大神你好，安装配置完mailProvider后，按照步骤启动，启动完成有pid提示，然后查看状态就是stopped？请问这是什么原因呢，查看日志nohup: failed to run command ‘./falcon-mail-provider’: No such file or directory

**Comment by phantoo0809** [comment]
我下载的源码，也没有falcon-mail-provider，然后按照 @wangyf123 方法，但是我到go get ./...，就报错[root@master mail-provider]# go get ./...
# cd .; git clone https://github.com/toolkits/file /root/go/src/github.com/toolkits/file
Cloning into '/root/go/src/github.com/toolkits/file'...
fatal: unable to access 'https://github.com/toolkits/file/': Could not resolve host: github.com; Unknown error
package github.com/toolkits/file: exit status 128
# cd .; git clone https://github.com/toolkits/smtp /root/go/src/github.com/toolkits/smtp
Cloning into '/root/go/src/github.com/toolkits/smtp'...
fatal: unable to access 'https://github.com/toolkits/smtp/': Could not resolve host: github.com; Unknown error
package github.com/toolkits/smtp: exit status 128
# cd .; git clone https://github.com/toolkits/web /root/go/src/github.com/toolkits/web
Cloning into '/root/go/src/github.com/toolkits/web'...
fatal: unable to access 'https://github.com/toolkits/web/': Could not resolve host: github.com; Unknown error
package github.com/toolkits/web/param: exit status 128
然后，我就按照报错里面的https://github.com/toolkits/这个网址，分别下载了file，smtp，web，解压到我goroot路径目录的toolkits目录下（/root/go/src/github.com/toolkits）里，当然你解压完还要把目录名改成对应的，直接解压完后面带个-master后缀，改一下名字就行，然后到goroot路径目录下的mail-provider中（我的是/root/go/src/github.com/open-falcon/mail-provider），直接
3、执行命令： ./control build (编译)
就有这个文件了

**Comment by laiwei** [comment]
mail-provider 需要从源码编译为二进制才能运行。

**Comment by phantoo0809** [comment]
感谢您百忙之中抽出时间回复我，是的，问题已经解决了，刚接触open-falcon，有很多小白问题，在github的issue的回复里发现答案了，也加了qq群，在qq群里也有很多人给我解答，有问题还会再提的，哈哈。



phantoo0809@163.com
 
发件人： laiwei
发送时间： 2018-02-28 16:52
收件人： open-falcon/mail-provider
抄送： phantoo0809; State change
主题： Re: [open-falcon/mail-provider] 单机安装的falconplus，mailprovider修改配置后，一起动就停止？ (#14)
mail-provider 需要从源码编译为二进制才能运行。
