### ISSUE TITLE
address format error

### ISSUE THREAD

**Issue by fengallan0** [open-falcon/mail-provider#22]
[root@fqy-log-1 mail-provider]# curl http://127.0.0.1:4000/sender/mail -d "tos=517089038@qq.com&subject=123&content=23"
address format error

请问下这个是什么原因呢

**Comment by DoubleShadowLZF** [comment]
大佬 我也是这样子

**Comment by rui-zhu** [comment]
问题没有一个人回答也是醉了

**Comment by freedomkk-qfeng** [comment]
> {
> "debug": true,
> "http": {
> "listen": "0.0.0.0:4000",
> "token": ""
> },
> "smtp": {
> "type": "smtp_ssl",
> "addr": "smtp.xx.com",
> "port": 25,
> "username": "邮件地址base64后的密文",
> "password": "密码base64后的密文",
> "from": "from地址base64后的密文",
> "tls":false,
> "anonymous":false,
> "skipVerify":true
> }
> }
> 
> 这样就报address format error
> 
> 变成 "addr": "mail.example.com:25", 就报unencrypted connection
> 
> 这是为什么呢？

你这个配置看上去似乎是之前的某个 fork 的版本。现在主干版本已经支持 ssl。拉主干代码重新编译用新版本试试。或者使用 [canghai908](https://github.com/canghai908) 提供的编译好的二进制包：`https://dl.cactifans.com/open-falcon/falcon-mail-provider.tar.gz`

可以通过如下命令来确认版本号，现在的版本是 0.0.2
```
# ./falcon-mail-provider -v
0.0.2
```

**Comment by lovegqin** [comment]
现在的版本确实是 0.0.2
以上的配置是在群里一个网友回答的。
以下配置后，会报unencrypted connection 
{
    "debug": true,
    "http": {
        "listen": "0.0.0.0:4000",
        "token": ""
    },
    "smtp": {
        "addr": "私有smtp地址:25",
        "username": "邮件地址base64后的密文",
        "password": "密码base64后的密文",
        "from": "邮件地址base64后的密文",
        "tls":false,
        "anonymous":false,
        "skipVerify":true
    }
}

**Comment by freedomkk-qfeng** [comment]
> unencrypted connection

这是因为 golang 的 smtp 库中，smtp 认证必须建立在 tls 隧道上，否则认为是不安全的（密码明文了就）。所以这说明你的服务器不支持在 25 端口上建立 starttls。
你把 tls 配置打成 true，直接开到 465 端口上看看？如果服务器支持的话。

**Comment by lovegqin** [comment]
> 
> 
> > unencrypted connection
> 
> 这是因为 golang 的 smtp 库中，smtp 认证必须建立在 tls 隧道上，否则认为是不安全的（密码明文了就）。所以这说明你的服务器不支持在 25 端口上建立 starttls。
> 你把 tls 配置打成 true，直接开到 465 端口上看看？如果服务器支持的话。

十分感谢，已成功
