### ISSUE TITLE
where is the falcon-mail-provider

### ISSUE THREAD

**Issue by GuoHongke** [open-falcon/mail-provider#3]

**Comment by wangyf123** [comment]
Have no idea, too.
`./var/app.log:nohup: failed to run command ‘./falcon-mail-provider’: No such file or directory`

**Comment by huangyisan** [comment]
需要进行编译，先编译，然后才有的。

**Comment by NotesFire** [comment]
hey,
  运行时提示这个要如何编译？
nohup: 无法运行命令"./falcon-mail-provider": 没有那个文件或目录

**Comment by huangyisan** [comment]
下载下来的是个go的源码文件，不是二进制文件，你可以参考官方文档源码安装，照样画葫芦，随便找个模块编译的方式进行编译，编译完后会生成falcon-mail-provider这个文件，到时候就可以使用命令启动了。

**Comment by KeithTt** [comment]
@huangyisan 13可以，弄好了

**Comment by wangyf123** [comment]
编译方法：
1、cd mail-provider （mail-provider存放在GOPATH/github/open-falcon目录下）
2、执行命令：go get ./...    (这条命令的作用大概是解决包依赖，会把需要的包从go官网或github下载到本地)
3、执行命令： ./control build  (编译)
4、执行命令： ./control pack (打包)

**Comment by ImDoubt** [comment]
怎么搞 啊，这个目录怎么有的GOPATH/github/open-falcon，求解答

**Comment by lqzhgood** [comment]
如果直接 二进制 安装，只需要把目录下 mail-provider 改名为 falcon-mail-provider 即可
